# Generated by Django 3.2.9 on 2021-12-01 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_auto_20211130_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurements',
            options={'verbose_name': 'Показания', 'verbose_name_plural': 'Показания'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Датчик', 'verbose_name_plural': 'Датчики'},
        ),
        migrations.AddField(
            model_name='measurements',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='measurement.sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='measurements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measure', to='measurement.measurements'),
        ),
    ]
