# Generated by Django 3.2.9 on 2021-12-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_auto_20211201_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='measurements',
        ),
    ]
