# Generated by Django 3.2.9 on 2021-12-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_remove_sensor_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='measurement.sensor'),
            preserve_default=False,
        ),
    ]
